version: 2

sources:
  - name: banksphere_raw
    schema: banksphere_raw

    tables:
      - name: branches
      - name: customers
      - name: accounts
      - name: transactions
      - name: cards
      - name: loans
      - name: loan_payments